server:
  port: 8082

spring:
  application:
    name: TICKET-SERVICE

resilience4j:
  circuitbreaker:
    instances:
      artistService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      artistService:
        maxAttempts: 3
        waitDuration: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
